import type { Request, Response } from "express";
import userSchema from "../model/userSchema.ts";
import { comparePasswords, hashPassword } from "../utils/hashPassword.ts";
import { generateToken } from "../utils/jwt.ts";
import mongoose from "mongoose";
import crypto from "crypto";
export const loginController = async (req: Request, res: Response) => {
  try {
    const { email, password } = req.body;
    const user = await userSchema.findOne({ email });
    if (!user) {
      return res.status(401).json({ message: "Invalid user  credentials" });
    }
    const isValidPassword = await comparePasswords(password, user.password);
    if (!isValidPassword) {
      return res.status(401).json({ message: "Invalid user  credentials" });
    }
    const token = await generateToken({
      id: user._id.toString(),
      email: user.email,
      role: user.role,
    });
    res.status(200).json({ message: "Login successful", token: token });
  } catch (error) {
    console.log(error);

    res.status(500).json({ message: "server error" });
  }
};
export const registerController = async (req: Request, res: Response) => {
  try {
    const { role, email, password, firstName, lastName } = req.body;
    const userName = `${firstName} ${lastName}`.trim();

    const existingEmail = await userSchema.findOne({ email });
    if (existingEmail) {
      return res.status(409).json({
        message: "Email already exists",
      });
    }

    const existingUsername = await userSchema.findOne({ userName });
    if (existingUsername) {
      return res.status(409).json({
        message: "Username already exists",
      });
    }

    const user = await userSchema.create({
      role,
      email,
      firstName,
      lastName,
      password: await hashPassword(password),
    });
    const token = await generateToken({
      id: user._id.toString(),
      email: user.email,
      role: user.role,
    });
    res
      .status(201)
      .json({ message: "user created successfully", token: token });
    console.log(user);
  } catch (error) {
    console.log(error);

    if (error instanceof mongoose.Error.ValidationError) {
      const errors = Object.values(error.errors).map((err) => ({
        field: err.path,
        message: err.message,
      }));
      return res.status(400).json({
        error: "Validation error",
        details: errors,
      });
    }

    res.status(500).json({ message: "server error" });
  }
};

export const googleSignInController = async (req: Request, res: Response) => {
  try {
    const { name, email, role } = req.body;

    // Split name into firstName and lastName
    const nameParts = name.trim().split(/\s+/);
    const firstName = nameParts[0] || name;
    const lastName = nameParts.slice(1).join(" ") || nameParts[0] || name;

    // Check if user already exists
    let user = await userSchema.findOne({ email });

    if (user) {
      // User exists, generate token and return
      const token = await generateToken({
        id: user._id.toString(),
        email: user.email,
        role: user.role,
      });
      return res.status(200).json({
        message: "Google sign-in successful",
        token: token,
      });
    }

    // User doesn't exist, create new user
    // Generate a random secure password for Google users (they won't need it)
    const randomPassword = crypto.randomBytes(32).toString("hex");
    const hashedPassword = await hashPassword(randomPassword);

    // userName will be auto-generated by pre-save hook
    user = await userSchema.create({
      role,
      email,
      firstName,
      lastName,
      password: hashedPassword,
    });

    const token = await generateToken({
      id: user._id.toString(),
      email: user.email,
      role: user.role,
    });

    res.status(201).json({
      message: "User created successfully via Google sign-in",
      token: token,
    });
  } catch (error) {
    console.log(error);

    res.status(500).json({ message: "server error" });
  }
};
